bp_mgmt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login

from bp_setup.forms import BPAuthenticationForm

admin.site.site_header = 'Administration: BP Allgemeinmedizin'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^setup/', include('bp_setup.urls', namespace='bp_setup')),
    url(r'^info/', include('django.contrib.flatpages.urls')),
    url(r'^/?', include('bp_cupid.urls', namespace='bp_cupid')),
    url(r'^login/$', login,
        {'authentication_form': BPAuthenticationForm},
        name='login',
    ),
    url('^', include('django.contrib.auth.urls')),
]

bp_setup/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from bp_setup import views

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^fragebogen/$', views.Fragebogen.as_view(), name='fragebogen'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bp_setup/models.py
from django.db import models

# Create your models here.

bp_setup/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ValidationError
from django_auth_ldap3.backends import LDAPBackend
from django_auth_ldap3.conf import settings

from bp_cupid.models import (
    Student,
)

import logging
logger = logging.getLogger(__name__)


class BPAuthenticationForm(AuthenticationForm):
    """
    Unser eigenes Authentifizierungsformular für das BP.
    """
    def clean(self):
        """
        Wenn sich ein Student einloggen will, müssen wir ein lokales
        Studentenobjekt erzeugen, in der wir die BP-Vorlieben speichern. Die
        erforderlichen Daten holen wir uns mittels LDAP vom Rechenzentrum.
        """
        cleaned_data = super(self.__class__, self).clean()

        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        ldap_backend = LDAPBackend()
        ldap_user = ldap_backend.bind_ldap_user(username, password)

        # Falls kein LDAP User existiert, probieren wir lokal weiter:
        if not ldap_user:
            return cleaned_data

        # der lokale User müsste schon erzeugt worden sein
        user = User.objects.get(username=username)

        connection = ldap_user.connection
        search_filter = '({}={})'.format(settings.UID_ATTRIB, username)

        # so heißen die Attribute auf dem LDAP-Server:
        mat_nr_attr = 'sos-mtknr'
        gender_attr = 'uniRGender'

        attributes = ldap_backend.search_ldap(
            connection,
            search_filter,
            attributes=[mat_nr_attr, gender_attr],
            size_limit=1,
        )

        mat_nr = int(attributes[mat_nr_attr][0])
        weiblich = attributes[gender_attr][0] == 'W'

        """
        Hier holen wir das lokale Studentenobjekt und speichern die relevanten
        Daten. Leider sind ein paar Daten wie Name und E-Mail-Adresse redundant,
        aber was willste machen.
        """
        try:
            student = Student.objects.get(mat_nr=mat_nr)
            student.user = user
            student.name = user.last_name
            student.vorname = user.first_name
            student.email = user.email
            student.weiblich = weiblich
            student.save()
        except Student.DoesNotExist:
            raise ValidationError(
                'Nicht zugelassen.'
            )

        return cleaned_data

bp_setup/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import View

from actstream import action
import logging
logger = logging.getLogger(__name__)

from bp_cupid.models import (
    Landkreis,
    Praxis,
    Student,
)


class Index(View):
    template_name = 'bp_setup/index.html'

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: Student.objects.filter(user=u).exists()))
    def get(self, request):
        student = Student.objects.get(user=request.user)

        if student.hat_platz():
            platz = student.platz
        else:
            platz = None

        context = {
            'student': student,
            'platz': platz,
        }

        return render(request, self.template_name, context)


class Fragebogen(View):
    template_name = 'bp_setup/fragebogen.html'

    @method_decorator(login_required)
    def get(self, request):
        """
        Zeigt den Fragebogen für Studenten an.
        """
        context = self.common_context(request)
        student = context['student']

        if student and student.hat_fragebogen_ausgefuellt:
            messages.add_message(
                request,
                messages.INFO,
                'Clever! Aber leider hast du den Fragebogen schon ausgefüllt.',
            )
            return redirect('bp_setup:index')
        else:
            return render(request, self.template_name, context)


    @method_decorator(login_required)
    def post(self, request):
        """
        Speichert die Daten des Fragebogens ab.
        """

        context = self.common_context(request)
        student = context['student']

        # erst aufräumen:
        for praxis in student.bevorzugte_praxen.all():
            student.bevorzugte_praxen.remove(praxis)

        for praxis in student.abgeneigte_praxen.all():
            student.abgeneigte_praxen.remove(praxis)

        for landkreis in student.landkreise.all():
            student.landkreise.remove(landkreis)

        # dann die Daten des Fragebogens speichern:
        besondere_kriterien = request.POST.get('besondere_praxiskriterien', '')
        student.besondere_praxiskriterien = besondere_kriterien

        gew_kinder = int(request.POST.get('kinder', 0))
        student.gewichtung_kinder = gew_kinder

        gew_sono = int(request.POST.get('sono', 0))
        student.gewichtung_sono = gew_sono

        gew_sport = int(request.POST.get('sport', 0))
        student.gewichtung_sport = gew_sport

        gew_kompl = int(request.POST.get('kompl', 0))
        student.gewichtung_kompl = gew_kompl

        gew_hohe_duene = int(request.POST.get('hoheduene', 0))
        student.gewichtung_hohe_duene = gew_hohe_duene

        fs_und_fahrzeug = bool(int(request.POST.get('fsundauto', 0)))
        student.fs_und_fahrzeug = fs_und_fahrzeug

        gewaehlte_praxen_ids = map(int, request.POST.getlist('praxis'))
        if gewaehlte_praxen_ids:
            gewaehlte_praxen = Praxis.objects.filter(id__in=gewaehlte_praxen_ids)
            for praxis in gewaehlte_praxen:
                student.bevorzugte_praxen.add(praxis)

        gewaehlte_landkreise_ids = map(int, request.POST.getlist('landkreis'))
        gewaehlte_landkreise = Landkreis.objects.filter(id__in=gewaehlte_landkreise_ids)
        for landkreis in gewaehlte_landkreise:
            student.landkreise.add(landkreis)

        uebernachtung = bool(int(request.POST.get('uebernachtung', 0)))
        adresse_priv_unterkunft = request.POST.get('uebernachtungsort', '')

        student.priv_unterkunft = uebernachtung
        student.adresse_priv_unterkunft = adresse_priv_unterkunft

        sonstiges = request.POST.get('ergaenzungen', '')
        student.sonstiges = sonstiges

        telefonnummer = request.POST.get('telefonnummer', '')
        student.telefonnummer = telefonnummer

        student.hat_fragebogen_ausgefuellt = True

        student.save()

        messages.add_message(
            request,
            messages.SUCCESS,
            'Vielen Dank für’s Ausfüllen!',
        )

        action.send(
            request.user,
            verb='füllte den Fragebogen aus'
        )

        return redirect('bp_setup:index')


    @staticmethod
    def common_context(request):
        besondere_la_praxen_ids = [10, 46, 59]
        besondere_la_praxen = Praxis.objects.filter(
            id__in=besondere_la_praxen_ids,
        )

        landkreise = Landkreis.objects.order_by('plz_von')

        try:
            student = request.user.student
        except Student.DoesNotExist:
            student = None

        context = {
            'besondere_la_praxen': besondere_la_praxen,
            'student': student,
            'landkreise': landkreise,
        }

        return context

bp_setup/templates/bp_setup/fragebogen.html
{% extends "bp_cupid/base.html" %}

{% load staticfiles %}

{% block javascript %}
<script>
$(document).ready(function() {
  $('#uebernachtung1').change(function() {
    $('#uebernachtungsort').prop('disabled', false);
  });

  $('#uebernachtung0').change(function() {
    $('#uebernachtungsort').val('');
    $('#uebernachtungsort').prop('disabled', true);
  });
});

function validiere_Landkreise() {
  var landkreise = $("[name=landkreis]");
  var anzahl_gewaehlter_landkreise = 0;
  var richtige_anzahl = false;

  landkreise.each(function() {
    if ($(this).is(":checked")) {
      anzahl_gewaehlter_landkreise += 1;
    }
  });

  richtige_anzahl = anzahl_gewaehlter_landkreise == 3;

  if (! richtige_anzahl) {
    $('#landkreiswarnung').toggle(true);
  }

  return richtige_anzahl;
}

function validiere_priv_Unterkunft() {
  var adresse_private_unterkunft = "";
  if ($("#uebernachtung1").is(":checked")) {
    adresse_private_unterkunft = $("#uebernachtungsort").val().trim()
    if (adresse_private_unterkunft == "") {
      $("#uebernachtungswarnung").toggle(true);
      return false;
    }
  }
  return true;
}

function validiere_Telefonnummer() {
  var telefonnummern_regex = /^\+?\d{9,15}$/;
  var telefonnummer = $.trim($("#telefonnummer").val());

  if (telefonnummer) {
    if (telefonnummern_regex.test(telefonnummer)) {
      return true;
    } else {
      $("#telefonnummernwarnung").toggle(true);
      return false;
    }
  } else {
    return true;
  }
}

function validiere_Fragebogen() {
  var checks = [
    validiere_Landkreise(),
    validiere_priv_Unterkunft(),
    validiere_Telefonnummer(),
  ];

  var i = 0;
  for (i = 0; i < checks.length; i++) {
    if (!checks[i]) {
      $('#fragebogenwarnung').toggle(true);
      return false;
    }
  }

  return true;
}
</script>
{% endblock javascript %}

{% block content %}
<div class="container-fluid">
  <form action="{% url 'bp_setup:fragebogen' %}" method="post" accept-charset="utf-8" onsubmit="return validiere_Fragebogen()">
    <div class="row">
      <div class="col-sm-12 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
        {% csrf_token %}
        <h2>Fragebogen an die Studierenden zum Blockpraktikum Allgemeinmedizin <small>WS 2016-17 und SS 2017</small></h2>
        {% if not student %}
        <div class="alert alert-warning">
          Mit Ihrem Account ist kein Student verknüpft.
          Falls Sie sich als Student eingeloggt haben,
          melden Sie sich bitte bei uns.
        </div>
        {% endif %}
        <p>
          Liebe Studierende,<br />
          insgesamt gilt es, im gesamten Studienjahr ca. 240 Studentinnen und
          Studenten auf 70 Lehrarztpraxen in Rostock und dem übrigen
          Mecklenburg-Vorpommern zu unterschiedlichen Zeiträumen einzuteilen.
          Wir laden Sie daher herzlich ein, diesen Fragebogen auszufüllen,
          damit wir die möglichst passende Lehrarztpraxis für Ihr
          Blockpraktikum Allgemeinmedizin finden können und die Wünsche aller
          Studierenden möglichst gleichmäßig und gerecht berücksichtigt werden.
        </p>
        <p>
          Bitte geben Sie an, an welchen <strong>Praxiskriterien</strong> Sie im
          Blockpraktikum Allgemeinmedizin <strong>sehr großes</strong> Interesse,
          <strong>etwas</strong> Interesse bzw. <strong>kein</strong> Interesse haben.
        </p>
        <div class="form-group">
          <p>
            <strong>1.</strong> Ich habe Interesse daran, dass in meiner Blockpraktikumspraxis
            regelmäßig <strong>Kinder und Jugendliche</strong> behandelt werden.
          </p>
          <div class="radio">
            <label>
              <input type="radio" name="kinder" id="kinder2" value="2">
              sehr großes Interesse
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="kinder" id="kinder1" value="1">
              etwas Interesse
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="kinder" id="kinder0" value="0">
              kein Interesse
            </label>
          </div>
        </div>
        <div class="form-group">
          <p>
            <strong>2.</strong> Ich habe Interesse daran, dass in meiner Blockpraktikumspraxis die
            Möglichkeit besteht, <strong>Sonografie</strong> unter Anleitung durchzuführen.
          </p>
          <div class="radio">
            <label>
              <input type="radio" name="sono" id="sono2" value="2">
              sehr großes Interesse
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="sono" id="sono1" value="1">
              etwas Interesse
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="sono" id="sono0" value="0">
              kein Interesse
            </label>
          </div>
        </div>
        <div class="form-group">
          <p>
            <strong>3.</strong> Ich habe Interesse daran, dass in meiner Blockpraktikumspraxis
            Patienten <strong>sportmedizinisch</strong> betreut werden.
          </p>
          <div class="radio">
            <label>
              <input type="radio" name="sport" id="sport2" value="2">
              sehr großes Interesse
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="sport" id="sport1" value="1">
              etwas Interesse
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="sport" id="sport0" value="0">
              kein Interesse
            </label>
          </div>
        </div>
        <div class="form-group">
          <p>
            <strong>4.</strong> Ich habe Interesse daran, dass in meiner Blockpraktikumspraxis auch
            <strong>komplementärmedizinische</strong> Verfahren angewendet werden.
          </p>
          <div class="radio">
            <label>
              <input type="radio" name="kompl" id="kompl2" value="2">
              sehr großes Interesse
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="kompl" id="kompl1" value="1">
              etwas Interesse
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="kompl" id="kompl0" value="0">
              kein Interesse
            </label>
          </div>
        </div>
        <div class="form-group">
          <p>
            <strong>5.</strong> Ich kann es mir gut vorstellen, die allgemeinmedizinische
            Versorgung von Patienten an einem <strong>Bundeswehrstandort</strong> kennenzulernen.
          </p>
          <div class="radio">
            <label>
              <input type="radio" name="hoheduene" id="hoheduene2" value="2">
              sehr großes Interesse
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="hoheduene" id="hoheduene1" value="1">
              etwas Interesse
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="hoheduene" id="hoheduene0" value="0">
              kein Interesse
            </label>
          </div>
        </div>
        <div class="form-group">
          <p>
            <strong>6.</strong> Besitzen Sie einen <strong>Führerschein</strong> und verfügen für die
            Dauer des Blockpraktikums über ein <strong>Fahrzeug</strong>?
          </p>
          <div class="radio">
            <label>
              <input type="radio" name="fsundauto" id="fsundauto1" value="1">
              ja, ich besitze einen Führerschein <strong>und</strong> ich
              verfüge über ein Fahrzeug
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="fsundauto" id="fsundauto0" value="0">
              nein
            </label>
          </div>
        </div>
        <div class="form-group">
          <p>
            <strong>7.</strong> Etwa die Hälfte unserer Lehrarztpraxen befindet sich direkt in
            Rostock, die andere Hälfte befindet sich in den auf der Karte
            dargestellten Regionen. (Zum Vergrößern bitte draufklicken.)
          </p>
          <a href="{% static 'bp_setup/img/mv-map.png' %}" target="_blank">
            <img src="{% static 'bp_setup/img/mv-map.png' %}" class="img-responsive" alt="Regionen in MV"/>
          </a>
          <p>
            Bitte wählen Sie aus den folgenden Landkreisen
            <strong>genau 3</strong> aus, bei denen Sie sich vorstellen können,
            Ihr Blockpraktikum zu absolvieren.  Beachten Sie bitte, dass Ihre
            Präferenzen bei weniger als 3 gewählten Landkreisen nicht
            berücksichtigt werden können.
          </p>
          <p>
            Zusatzinformation: Die Kassenärztliche Vereinigung erstattet Ihnen
            die Fahrtkosten zu den weiter entfernt liegenden Praxen in
            Mecklenburg-Vorpommern.
          </p>
          <div class="alert alert-danger" id="landkreiswarnung" style="display: none;">
            Bitte wählen Sie genau 3 Landkreise aus.
          </div>
          {% for landkreis in landkreise %}
          <div class="checkbox">
            <label>
              <input type="checkbox" name="landkreis" id="landkreis{{ landkreis.id }}" value="{{ landkreis.id }}">
              Bereich {{ landkreis.name }} (Praxen in {{ landkreis.orte }})
            </label>
          </div>
          {% endfor %}
        </div>
        <div class="form-group">
          <p>
            <strong>8.</strong> Haben Sie in den genannten Landkreisen eine
            <strong>private Übernachtungsmöglichkeit</strong>, z.&thinsp;B. bei
            Verwandten oder Freunden?
          </p>
          <p>
            Falls ja, geben Sie bitte den Ort und möglichst auch die Postleitzahl an.
          </p>
          <div class="alert alert-danger" id="uebernachtungswarnung" style="display: none;">
            Bitte geben Sie Ort + PLZ an.
          </div>
          <div class="form-inline">
            <label class="radio-inline">
              <input type="radio" name="uebernachtung" id="uebernachtung1" value="1">
              ja, in
            </label>
            <input type="text" style="width: 50%;" class="form-control input-sm" name="uebernachtungsort" id="uebernachtungsort" placeholder="PLZ + Ort" disabled>
          </div>
          <label class="radio-inline">
            <input type="radio" name="uebernachtung" id="uebernachtung0" value="0">
            nein
          </label>
        </div>
        <div class="form-group">
          <p>
            <strong>9.</strong> Die folgenden Lehrarztpraxen liegen im ländlichen Raum und bieten
            neben einer intensiven Betreuung der Studierenden eine
            <strong>kostenfreie Unterkunft</strong> für die Zeit des
            Blockpraktikums an. In den vergangenen Jahren wurden die
            Blockpraktika in diesen Praxen von Ihren Kommilitonen durchweg sehr
            positiv bewertet.
          </p>
          <p>
            Ich kann mir gut vorstellen, mein Blockpraktikum in einer der
            folgenden Praxen durchzuführen:
          </p>
          {% for praxis in besondere_la_praxen %}
          <div class="checkbox checkbox-praxis">
            <label>
              <input type="checkbox" name="praxis" id="praxis{{ praxis.id }}" value="{{ praxis.id }}">
              {{ praxis.anrede }} {{ praxis.titel }} {{ praxis.vorname }} {{ praxis.name }},
              <a href="{{ praxis.maps_link }}" target="_blank"><i class="fa fa-globe"></i> {{ praxis.plz }} {{ praxis.ort }}</a>
            </label>
          </div>
          {% endfor %}
        </div>
        <div class="form-group">
          <p>
            Haben Sie weitere wichtige Mitteilungen zur Vergabe des
            Blockpraktikumsplatzes an uns?
          </p>
          <textarea class="form-control" rows="5" name="ergaenzungen" id="ergaenzungen" value=""></textarea>
        </div>
        <div class="form-group">
          <p>
            Nach dem Blockpraktikum würden wir Sie für die Evaluation gerne
            kontaktieren. Wenn Sie uns Feedback geben möchten, geben Sie hier
            Ihre Telefonnummer an:
          </p>
          <div class="alert alert-danger" id="telefonnummernwarnung" style="display: none;">
            Bitte geben Sie eine korrekte Telefonnummer im Format
            <code>+493814942481</code> an.
          </div>
          <div class="row">
            <div class="col-md-5">
              <input type="tel" class="form-control" name="telefonnummer" id="telefonnummer">
            </div>
          </div>
        </div>
        <p>
          Sie sind nun am Ende des Fragebogens angelangt.
        </p>
        <p>
          Herzlichen Dank für Ihre Angaben!
        </p>
        <p>
          Über Ihre Einteilung für das Blockpraktikum werden Sie Ende Juli per
          E-Mail informiert. Weitere Informationen finden Sie auf unserer
          <a href="#" target="_blank">Homepage</a>.
        </p>
        <div class="alert alert-danger" id="fragebogenwarnung" style="display: none;">
          Bitte korrigieren Sie die Fehler und schicken Sie die Daten erneut ab!
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary"{% if not student %} disabled="disabled"{% endif %}>Abschicken</button>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

bp_setup/templates/bp_setup/index.html
{% extends "bp_cupid/base.html" %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-offset-1 col-lg-5 col-md-6">
      <h2>Hallo {{ student.vorname }},</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-offset-1 col-lg-4 col-md-6">
      <p>
        zur Kontrolle listen wir hier ein paar allgemeine Daten auf:
      </p>
      <table class="table table-condensed">
        <tr>
          <th class="col-lg-4">Name</th>
          <td>{{ student.vorname }} {{ student.name }}</td>
        </tr>
        <tr>
          <th>Matrikelnummer</th>
          <td>{{ student.mat_nr }}</td>
        </tr>
        <tr>
          <th>E-Mail-Adresse</th>
          <td>{{ student.email }}</td>
        </tr>
        <tr>
           <th>Verwaltungszeitraum</th>
           <td>{{ student.verwaltungszeitraum }}</td>
        </tr>
        {% if student.telefonnummer %}
        <tr>
          <th>Telefonnummer</th>
          <td>{{ student.telefonnummer }}</td>
        </tr>
        {% endif %}
        <tr>
          <th>Geschlecht</th>
          <td>
            {% if student.weiblich %}
            <abbr title="weiblich" class="initialism"><i class="fa fa-venus"></i></abbr>
            {% else %}
            <abbr title="männlich" class="initialism"><i class="fa fa-mars"></i></abbr>
            {% endif %}
          </td>
        </tr>
      </table>
      <p>
        Falls davon irgendwas unstimmig sein sollte,
        <a href="mailto:">melden Sie sich</a>
        bitte bei uns.
      </p>
      <h3>Ihr Platz</h3>
      {% if platz %}
      <table class="table table-condensed">
        <tr>
          <th>Praxis</th>
          <td>
            <p>
              {{ platz.praxis.anrede }} {{ platz.praxis.vorname }} {{ platz.praxis.name }}<br />
              {{ platz.praxis.adresse }}<br />
              {{ platz.praxis.plz }} {{ platz.praxis.ort }}<br />
              <i class="fa fa-phone"></i> {{ platz.praxis.telefon }}
            </p>
          </td>
        </tr>
        <tr>
          <th>Zeitraum</th>
          <td>
            {{ platz.zeitraum.anfang|date:"d. F Y" }} bis {{ platz.zeitraum.ende|date:"d. F Y" }}
          </td>
        </tr>
      </table>
      {% else %}
      <p>
        Ihnen wurde noch kein Platz zugeteilt.
      </p>
      {% endif %}
      {% if messages %}
      {% for message in messages %}
      <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
    </div>
    <div class="col-lg-offset-1 col-lg-5 col-md-6">
      {% if student.hat_fragebogen_ausgefuellt %}
      <p>
        Folgende Daten haben wir gespeichert:
      </p>
      <table class="table table-condensed">
        <tr>
          <th class="col-lg-4">Kinder</th>
          <td>
            {% if student.gewichtung_kinder == 2 %}
            sehr großes
            {% elif student.gewichtung_kinder == 1 %}
            etwas
            {% else %}
            kein
            {% endif %}
            Interesse
          </td>
        </tr>
        <tr>
          <th>Sonografie</th>
          <td>
            {% if student.gewichtung_sono == 2 %}
            sehr großes
            {% elif student.gewichtung_sono == 1 %}
            etwas
            {% else %}
            kein
            {% endif %}
            Interesse
          </td>
        </tr>
        <tr>
          <th>Sportmedizin</th>
          <td>
            {% if student.gewichtung_sport == 2 %}
            sehr großes
            {% elif student.gewichtung_sport == 1 %}
            etwas
            {% else %}
            kein
            {% endif %}
            Interesse
          </td>
        </tr>
        <tr>
          <th>Komplementärmedizin</th>
          <td>
            {% if student.gewichtung_kompl == 2 %}
            sehr großes
            {% elif student.gewichtung_kompl == 1 %}
            etwas
            {% else %}
            kein
            {% endif %}
            Interesse
          </td>
        </tr>
        <tr>
          <th>Bundeswehr</th>
          <td>
            {% if student.gewichtung_hohe_duene == 2 %}
            sehr großes
            {% elif student.gewichtung_hohe_duene == 1 %}
            etwas
            {% else %}
            kein
            {% endif %}
            Interesse
          </td>
        </tr>
        <tr>
          <th>Führerschein und Auto</th>
          <td>
            {% if student.fs_und_fahrzeug %}
            <i class="fa fa-thumbs-o-up"></i>
            {% else %}
            <i class="fa fa-thumbs-o-down"></i>
            {% endif %}
          </td>
        </tr>
        <tr>
          <th>bevorzugte Landkreise</th>
          <td>
            {% for landkreis in student.landkreise.all %}
            {{ landkreis.plz_von }} – {{ landkreis.plz_bis }} ({{ landkreis.orte }})<br />
            {% endfor %}
          </td>
        </tr>
        <tr>
          <th>private Unterkunft</th>
          <td>
            {% if student.priv_unterkunft %}
            <i class="fa fa-thumbs-o-up"></i> ({{ student.adresse_priv_unterkunft }})
            {% else %}
            <i class="fa fa-thumbs-o-down"></i>
            {% endif %}
          </td>
        </tr>
        {% if student.bevorzugte_praxen.exists %}
        <tr>
          <th>bevorzugte Praxen</th>
          <td>
            {% for praxis in student.bevorzugte_praxen.all %}
            {{ praxis.anrede }} {{ praxis.name }}, {{ praxis.plz }} {{ praxis.ort }}<br />
            {% endfor %}
          </td>
        </tr>
        {% endif %}
        {% if student.sonstiges %}
        <tr>
          <th>weitere Mitteilungen</th>
          <td>{{ student.sonstiges }}</td>
        </tr>
        {% endif %}
      </table>
      <p>
        Über Ihre Einteilung für das Blockpraktikum werden Sie Ende Juli per
        E-Mail informiert. Weitere Informationen finden Sie auf unserer
        <a href="" target="_blank">Homepage</a>.
      </p>
      {% else %}
      <p>
        Bitte füllen Sie noch den <a href="{% url 'bp_setup:fragebogen' %}">Fragebogen</a> aus!
      </p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}