bp_cupid/api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from .views import VorlagenDetail


urlpatterns = [
    url(r'^vorlage/(?P<token>[-\w]+)/$', VorlagenDetail.as_view(), name='vorlage'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

bp_cupid/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from . import views
from . import api

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(regex=r'^api/', view=include(api.urls, namespace='api')),
    url(r'^status/$', views.Status.as_view(), name='status'),
    url(r'^einstellungen/$', views.Einstellungen.as_view(), name='einstellungen'),
    url(r'^gewichte/$', views.Gewichte.as_view(), name='gewichte'),
    url(r'^studenten/$', views.StudentList.as_view(), name='studenten'),
    url(r'^student/(?P<mat_nr>\d+)/$', views.StudentDetail.as_view(), name='student'),
    url(r'^praxen/$', views.PraxisList.as_view(), name='praxen'),
    url(r'^praxis/(?P<praxis_id>\d+)/$', views.PraxisDetail.as_view(), name='praxis'),
    url(r'^plaetze/$', views.Plaetze.as_view(), name='plaetze'),
    url(r'^platzuebersicht/$', views.Platzuebersicht.as_view(), name='platzuebersicht'),
    url(r'^zufaellig_verteilen/$', views.ZufaelligVerteilen.as_view(), name='zufaellig_verteilen'),
    url(r'^gezielt_verteilen/$', views.GezieltVerteilen.as_view(), name='gezielt_verteilen'),
    url(r'^zulassen/$', views.StudentenZulassen.as_view(), name='studenten_zulassen'),
    url(r'^bloecke/$', views.Bloecke.as_view(), name='bloecke'),
    url(r'^email/$', views.Email.as_view(), name='email'),
    url(r'^email/preview/$', views.EmailPreview.as_view(), name='preview_email'),
    url(r'^zusatzinfo/$', views.Zusatzinfo.as_view(), name='zusatzinfo'),
    url(r'^pdf/praxis/(?P<praxis_id>\d+)/$', views.PDFPraxis.as_view(), name='pdf_praxis'),
    url(r'^pdf/praxen/$', views.PDFPraxen.as_view(), name='pdf_praxen'),
    url(r'^excel/platzuebersicht/(?P<verwzr_id>\d+)$', views.ExcelPlatzuebersicht.as_view(), name='excel/platzuebersicht'),
    url(r'^evaluation/$', views.EvaluationList.as_view(), name='evaluation_uebersicht'),
    url(r'^evaluation/(?P<mat_nr>\d+)/$', views.EvaluationDetail.as_view(), name='evaluation'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bp_mgmt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login

from bp_setup.forms import BPAuthenticationForm

admin.site.site_header = 'Administration: BP Allgemeinmedizin'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^setup/', include('bp_setup.urls', namespace='bp_setup')),
    url(r'^info/', include('django.contrib.flatpages.urls')),
    url(r'^/?', include('bp_cupid.urls', namespace='bp_cupid')),
    url(r'^login/$', login,
        {'authentication_form': BPAuthenticationForm},
        name='login',
    ),
    url('^', include('django.contrib.auth.urls')),
]

bp_cupid/api/views.py
from rest_framework import generics

from .serializers import VorlagenSerializer

from ..models import Vorlage


class VorlagenDetail(generics.RetrieveAPIView):
    queryset = Vorlage.objects.all()
    serializer_class = VorlagenSerializer
    lookup_field = 'token'

bp_cupid/views/Bloecke.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.generic import View

from itertools import zip_longest


class Bloecke(View):
    template_name = 'bp_cupid/bloecke.html'

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def get(self, request):
        akt_verw_zr = request.user.mitarbeiter.akt_verw_zeitraum
        akt_bloecke = akt_verw_zr.bloecke.order_by('name')

        if akt_bloecke:
            platzlisten = [b.plaetze() for b in akt_bloecke]
            # Transponiere die Liste der Plätze, damit wir sie als Tabelle
            # darstellen können:
            blocklisten = zip_longest(*platzlisten)
        else:
            blocklisten = []

        context = {
            'bloecke': akt_bloecke,
            'blocklisten': blocklisten,
        }

        return render(request, self.template_name, context)

bp_cupid/views/Einstellungen.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import View

from ..models import Verwaltungszeitraum


class Einstellungen(View):
    template_name = 'bp_cupid/einstellungen.html'

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def get(self, request):
        """
        Zeigt das Formular für die Einstellungen an.
        """
        context = self.common_context(request.user.mitarbeiter)

        return render(request, self.template_name, context)


    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request):
        """
        Speichert die Einstellungen für einen Mitarbeiter.
        """
        mitarbeiter = request.user.mitarbeiter
        context = self.common_context(request.user.mitarbeiter)

        neue_verw_zr_id = int(request.POST.get('verwaltungszeitraum'))
        neuer_verw_zr = Verwaltungszeitraum.objects.get(id=neue_verw_zr_id)

        mitarbeiter.akt_verw_zeitraum = neuer_verw_zr
        mitarbeiter.save()

        context['akt_verw_zeitraum'] = neuer_verw_zr
        context['gespeichert'] = True

        return render(request, self.template_name, context)


    @staticmethod
    def common_context(mitarbeiter):
        akt_verw_zr = mitarbeiter.akt_verw_zeitraum
        verwzrs = Verwaltungszeitraum.objects.order_by('-anfang')

        context = {
            'akt_verw_zeitraum': akt_verw_zr,
            'verwzrs': verwzrs,
        }

        return context

bp_cupid/views/Email.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.mail import (
    EmailMessage,
    get_connection,
)
from django.http import HttpResponse
from django.shortcuts import render
from django.template import Template, Context
from django.template.base import TemplateSyntaxError
from django.utils.decorators import method_decorator
from django.utils.html import escape
from django.views.generic import View

from itertools import zip_longest

from ..models import (
    Vorlage,
    Platz,
    Student,
)


class Email(View):
    template_name = 'bp_cupid/email.html'
    vorlagen = Vorlage.objects.all()
    freie_studenten = Student.objects.frei().select_related(
        'verwaltungszeitraum'
    )


    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def get(self, request):
        """
        Zeigt das Formular für den E-Mail-Versand an.
        """
        akt_verw_zr = request.user.mitarbeiter.akt_verw_zeitraum
        akt_bloecke = akt_verw_zr.bloecke.order_by('name')

        context = {
            'bloecke': akt_bloecke,
            'blocklisten': self.blocklisten(akt_bloecke),
            'vorlagen': self.vorlagen,
            'freie_studenten': self.freie_studenten,
        }

        return render(request, self.template_name, context)


    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request):
        """
        Bastelt die E-Mails zusammen und verschickt sie an die gewählten
        Studenten.
        """
        mat_nrs = map(int, request.POST.getlist('student'))

        studenten = Student.objects.filter(mat_nr__in=mat_nrs).order_by('name')
        plaetze = Platz.objects.filter(student__in=studenten)

        betreff = request.POST.get('email-subject', '').strip()
        email_vorlage = Template(request.POST.get('email-content', '').strip())
        bcc_addr = request.POST.get('email-bcc', '').strip()
        testmail = 'testmail' in request.POST

        emails = []
        recps = []

        sender = 'Team Lehre der Allgemeinmedizin <team.lehre@med.uni-rostock.de>'

        for student in studenten:
            recp = '{} {} <{}>'.format(
                student.vorname,
                student.name,
                student.email,
            )
            try:
                platz = plaetze.get(student=student)
            except Platz.DoesNotExist:
                platz = None

            email = EmailMessage(
                subject=betreff,
                body=email_vorlage.render(
                    Context({'student': student, 'platz': platz})
                ),
                from_email=sender,
            )

            """
            Falls wir eine Testmail verschicken wollen, dann wird die generierte
            E-Mail an die Adresse vom BCC-Feld geschickt:
            """
            if testmail:
                email.to = [bcc_addr]
            else:
                email.to = [recp]
                email.bcc = [bcc_addr]

            emails.append(email)
            recps.append(recp)

        with get_connection() as connection:
            for email in emails:
                email.connection = connection
                email.send()

        """
        Zuletzt basteln wir noch den Hinweis über die versandten E-Mails
        zurecht:
        """
        if testmail:
            msg = """
            Diese Testmail wäre an folgende Studenten versandt worden:
            <ul>
            """
            msg_type = messages.INFO
        else:
            msg = """
            E-Mail wurde an folgende Studenten versandt:
            <ul>
            """
            msg_type = messages.SUCCESS

        for recp in recps:
            msg += '<li>{}</li>'.format(escape(recp))
        msg += '</ul>'

        messages.add_message(request, msg_type, msg)

        akt_bloecke = self.aktuelle_bloecke(
            request.user.mitarbeiter.akt_verw_zeitraum
        )
        context = {
            'bloecke': akt_bloecke,
            'blocklisten': self.blocklisten(akt_bloecke),
            'vorlagen': self.vorlagen,
            'freie_studenten': self.freie_studenten,
        }

        return render(request, self.template_name, context)


    @staticmethod
    def blocklisten(bloecke):
        if bloecke:
            platzlisten = [b.plaetze() for b in bloecke]
            # Transponiere die Liste der Plätze, damit wir sie als Tabelle
            # darstellen können:
            return zip_longest(*platzlisten)
        else:
            return []


    @staticmethod
    def aktuelle_bloecke(verwaltungszeitraum):
        return verwaltungszeitraum.bloecke.order_by('name')


class EmailPreview(View):
    def post(self, request):
        """
        Erstellt eine Vorschau der übergebenen Vorlage.
        Dazu wählen wir zufällig einen Studenten des aktuellen
        Verwaltungszeitraums aus, rendern die Vorlage mit diesen Daten und geben
        das Ergebnis zurück.
        """
        akt_verw_zr = request.user.mitarbeiter.akt_verw_zeitraum
        student = Student.objects.filter(
            verwaltungszeitraum=akt_verw_zr
        ).order_by('?').first()

        try:
            platz = student.platz
        except Platz.DoesNotExist:
            platz = None

        try:
            vorlagen_text = Template(request.POST.get('content', ''))
        except TemplateSyntaxError:
            vorlagen_text = Template('In der Vorlage ist ein Syntaxfehler!')

        context = Context({'student': student, 'platz': platz})
        preview = vorlagen_text.render(context)

        return HttpResponse(preview)

bp_cupid/views/Evaluation.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.generic import View

from actstream import action

from ..models import Platz, Evaluation
from ..forms import EvaluationForm

class EvaluationList(View):
    template_name = 'bp_cupid/evaluationenliste.html'

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def get(self, request):
        """
        Zeigt alle Plätze mit den Evaluationen an.
        """
        akt_verw_zr = request.user.mitarbeiter.akt_verw_zeitraum

        plaetze = Platz.objects.filter(
            student__verwaltungszeitraum=akt_verw_zr,
        ).order_by(
            'student__name',
        ).select_related(
            'student',
            'praxis',
            'zeitraum',
            'evaluation',
        )

        context = {
            'plaetze': plaetze,
        }

        return render(request, self.template_name, context)


class EvaluationDetail(View):
    form_class = EvaluationForm
    template_name = 'bp_cupid/evaluation.html'

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def get(self, request, mat_nr):
        """
        Zeigt das Evaluationsformular an.
        """

        platz = get_object_or_404(Platz, student__mat_nr=mat_nr)
        user = request.user

        initial_data = {
            'platz': platz,
            'eval_user': user,
        }

        """
        Falls schon eine Evaluation existiert, dann laden wir die Daten davon.
        """
        try:
            ev = platz.evaluation
        except Evaluation.DoesNotExist:
            ev = None

        form = self.form_class(initial=initial_data, instance=ev)

        context = {
            'form': form,
            'akt_datum': now(),
            'platz': platz,
        }

        return render(request, self.template_name, context)

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request, mat_nr):
        """
        Speichert eine Evaluation. Wenn schon eine Evaluation existiert, wird
        die alte überschrieben.
        """
        try:
            ev = Evaluation.objects.get(platz__student__mat_nr=mat_nr)
        except Evaluation.DoesNotExist:
            ev = None

        form = self.form_class(request.POST, instance=ev)

        if form.is_valid():
            neue_evaluation = form.save()

            if ev:
                action_verb = 'bearbeitete die Evaluation von'
            else:
                action_verb = 'evaluierte'

            action.send(
                request.user,
                verb=action_verb,
                target=neue_evaluation.platz.student,
            )

            return redirect('bp_cupid:evaluation_uebersicht')
        else:
            """
            Falls beim Formular ein Fehler aufgetreten ist, dann suchen wir uns
            wieder den Platz raus und stellen das Formular mit den bereits
            eingegebenen Daten dar:
            """
            platz = get_object_or_404(Platz, student__mat_nr=mat_nr)
            context = {
                'form': form,
                'akt_datum': now(),
                'platz': platz,
            }
            return render(request, self.template_name, context)

bp_cupid/views/Gewichte.py
from django.shortcuts import render, redirect
from django.core.cache import cache
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.views.generic import View

from actstream import action

from ..models import(
    Gewicht,
    Praxis,
    Student,
)
from ..tasks import berechne_gewichte, BERECHNE_GEWICHTE_LOCK_ID


class Gewichte(View):
    template_name = 'bp_cupid/gewichte.html'

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def get(self, request):
        """
        Zeigt die Berechnungsübersicht für die Gewichte an.
        """
        akt_verw_zr = request.user.mitarbeiter.akt_verw_zeitraum

        akt_anzahl_studenten = Student.objects.filter(
            verwaltungszeitraum=akt_verw_zr
        ).count()
        anzahl_praxen = Praxis.objects.count()
        akt_anzahl_gewichte = Gewicht.objects.filter(
            student__verwaltungszeitraum=akt_verw_zr
        ).count()

        context = {
            'laufende_Gewichtsberechnung': self.gewichtsberechnung_laeuft(),
            'akt_anzahl_studenten': akt_anzahl_studenten,
            'anzahl_praxen': anzahl_praxen,
            'anzahl_gewichte_soll': akt_anzahl_studenten * anzahl_praxen,
            'anzahl_gewichte_haben': akt_anzahl_gewichte,
        }

        return render(request, self.template_name, context)


    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request):
        """
        Startet die Gewichtsberechnung, falls nicht schon eine läuft.
        """
        if not self.gewichtsberechnung_laeuft():
            akt_verw_zr_id = request.user.mitarbeiter.akt_verw_zeitraum_id

            berechne_gewichte.delay(akt_verw_zr_id)
            action.send(
                request.user,
                verb='startete Gewichtsberechnung'
            )

        return redirect('bp_cupid:gewichte')


    def gewichtsberechnung_laeuft(self):
        return bool(cache.get(BERECHNE_GEWICHTE_LOCK_ID))

bp_cupid/templates/bp_cupid/einstellungen.html
{% extends "bp_cupid/base.html" %}

{% block content %}
<div class="container-fluid">
  <h2>Einstellungen</h2>
  <div class="row">
    {% if gespeichert %}
    <div class="col-md-4 col-lg-4">
      <div class="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        Einstellungen gespeichert!
      </div>
    </div>
    {% endif %}
  </div>
  <div class="row">
    <div class="col-md-6 col-lg-4">
      <form class="form-horizontal" action="{% url 'bp_cupid:einstellungen' %}" method="post" accept-charset="utf-8">
        {% csrf_token %}
        <div class="form-group">
          <label class="col-sm-4 col-md-6 col-lg-5 control-label" for="verwaltungszeitraum">aktueller Verwaltungszeitraum:</label>
          <div class="col-sm-8 col-md-6 col-lg-7">
            <select name="verwaltungszeitraum" id="verwaltungszeitraum" class="form-control">
              {% for verwzr in verwzrs %}
              <option value="{{ verwzr.id }}"{% if verwzr == akt_verw_zeitraum %} selected{% endif %}>{{ verwzr }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="text-right">
          <button type="submit" class='btn btn-primary'>Speichern</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

bp_cupid/templates/bp_cupid/evaluationenliste.html
{% extends "bp_cupid/base.html" %}
{% load l10n %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-lg-12">
      {% if plaetze %}
      <table class="table">
        <thead>
          <tr>
            <th class="col-md-2 col-lg-2">Name</th>
            <th class="col-md-3 col-lg-3">Praxis</th>
            <th class="col-md-2 col-lg-2">Zeitraum</th>
            <th></th>
            <th class="col-md-3 col-lg-3"></th>
          </tr>
        </thead>
        <tbody>
        {% for p in plaetze %}
          <tr>
            <td>{{ p.student.vorname }} {{ p.student.name }} ({{ p.student.mat_nr }})</td>
            <td>{{ p.praxis.vorname }} {{ p.praxis.name }}, {{ p.praxis.ort }}</td>
            <td>{{ p.zeitraum.anfang }} – {{ p.zeitraum.ende }}</td>
            {% if p.evaluation %}
            <td>
              <a class="btn btn-warning btn-sm" href="{% url 'bp_cupid:evaluation' p.student.mat_nr %}" role="button">bearbeiten</a>
            </td>
            <td>
              Evaluiert von {{ p.evaluation.eval_user.get_full_name }} am {{ p.evaluation.datum }}.
            </td>
            {% else %}
            <td>
              <a class="btn btn-primary btn-sm" href="{% url 'bp_cupid:evaluation' p.student.mat_nr %}" role="button">evaluieren</a>
            </td>
            <td></td>
            {% endif %}
          </tr>
        {% endfor %}
        </tbody>
      </table>
      {% else %}
      <p>Keine Plätze vorhanden.</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

bp_cupid/templates/bp_cupid/gezielt_verteilen.html
{% extends "bp_cupid/base.html" %}

{% block javascript %}
<script type="text/javascript">
$(window).load(function(){
  $('[data-toggle="popover"]').popover({
    container: 'body',
    html: 'true'
  });
});
</script>
{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-3 col-lg-2"> <!-- Übersicht der Verteilungen -->
      <ul class="nav nav-pills nav-stacked">
        <li role="presentation"><a href="{% url 'bp_cupid:zufaellig_verteilen' %}">zufällige Verteilung</a></li>
        <li role="presentation" class="active"><a href="{% url 'bp_cupid:gezielt_verteilen' %}">gezielte Verteilung</a></li>
      </ul>
      <p>
        <div class="alert alert-warning">
          <strong>Achtung:</strong> bei der Verteilung wird noch nicht die verfügbare Kapazität berücksichtigt.
          Falls du also mehr Studenten verteilen möchtest, als Plätze verfügbar sind, dann werden die übrigen einfach nicht verteilt.
          Eine Kapazitätsanzeige ist in Planung.
        </div>
      </p>
    </div>
    <div class="col-sm-9 col-md-9 col-lg-10"> <!-- Formular und Anzeige der verteilten Plätze -->
      <form action="{% url 'bp_cupid:gezielt_verteilen' %}" method="post" accept-charset="utf-8">
        {% csrf_token %}
        <div class="col-sm-6 col-md-6 col-lg-3">
          <div class="form-group">
            <label for="freie_studenten">Freie Studenten auswählen</label>
            <div id="freie_studenten" name="freie_studenten">
              {% for s in freie_studenten %}
              <div class="checkbox">
                <label><input type="checkbox" name="student" value="{{ s.mat_nr }}" /> {{ s.vorname }} {{ s.name }} ({{ s.mat_nr }})</label>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-6 col-lg-2">
          <div class="form-group">
            <label for="bloecke">Block auswählen</label>
            <div id="bloecke" name="bloecke">
              {% for b in bloecke %}
              <div class="radio">
                <label><input type="radio" name="block" value="{{ b.id }}"{% if forloop.first %} checked{% endif %}> {{ b.name }}</label>
              </div>
              {% endfor %}
            </div>
          </div>
          <div class="form-group">
            <label>und los:</label>
            <div>
              <button class="btn btn-primary btn-block" type="submit">Verteilen</button>
            </div>
          </div>
        </div>
        {% if plaetze %}
        <div class="col-sm-12 col-md-12 col-lg-6 col-lg-offset-1">
          <label>Verteilte Plätze</label>
          <table class="table table-bordered">
            <tr>
              <th>Student</th>
              <th>Praxis</th>
              <th>Zeitraum</th>
            </tr>
            {% for platz in plaetze %}
            <tr>
              <td>{{ platz.student.vorname }} {{ platz.student.name }} ({{ platz.student.mat_nr }})</td>
              <td>{{ platz.praxis.vorname }} {{ platz.praxis.name }}</td>
              <td>{{ platz.zeitraum.anfang }} – {{ platz.zeitraum.ende }}</td>
            </tr>
            {% endfor %}
          </table>
        </div>
        {% endif %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

bp_cupid/templates/bp_cupid/status.html
{% extends "bp_cupid/base.html" %}

{% block content %}
<div class="container-fluid">
  <div class="col-sm-6 col-md-6 col-lg-4">
    <h2>Status <small>{{ verwzr }}</small></h2>
    <table class="table">
      {% for k, v in fakten.items %}
      <tr>
        <td>{{ k }}</td><td>{{ v }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>
{% endblock %}

bp_cupid/templates/bp_cupid/zufaellig_verteilen.html
{% extends "bp_cupid/base.html" %}

{% block javascript %}
<script type="text/javascript">
function validiere_Bloecke() {
  var bloecke = $("#bloecke :checkbox");
  var irgendein_block_gecheckt = false;

  bloecke.each(function() {
    if ($(this).is(':checked')) {
      irgendein_block_gecheckt = true;
    }
  });

  if (! irgendein_block_gecheckt) {
    $('#blockwarnung').toggle(true);
  }

  return irgendein_block_gecheckt;
}

function alle_Bloecke_waehlen() {
  var bloecke = $("#bloecke :checkbox");

  bloecke.each(function() {
    $(this).prop('checked', true);
  });
}
</script>
{% endblock javascript %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-3 col-lg-2">
      <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="active" ><a href="{% url 'bp_cupid:zufaellig_verteilen' %}">zufällige Verteilung</a></li>
        <li role="presentation"><a href="{% url 'bp_cupid:gezielt_verteilen' %}">gezielte Verteilung</a></li>
      </ul>
      <p>
        <div class="alert alert-warning">
          <strong>Achtung:</strong> bei der Verteilung wird noch nicht die verfügbare Kapazität berücksichtigt.
          Falls du also mehr Studenten verteilen möchtest, als Plätze verfügbar sind, dann werden die übrigen einfach nicht verteilt.
          Eine Kapazitätsanzeige ist in Planung.
        </div>
      </p>
    </div>
    <div class="col-sm-9 col-md-9 col-lg-10">
      {% if laufende_Platzverteilung %}
      <div class="alert alert-info">
        Die Plätze werden gerade verteilt.
        Das dauert ungefähr eine Minute.
        Versuch’s mal mit <a href="{% url 'bp_cupid:zufaellig_verteilen' %}" class="alert-link">neu laden</a>.
      </div>
      {% endif %}
      <form action="{% url 'bp_cupid:zufaellig_verteilen' %}" method="post" accept-charset="utf-8" onsubmit="return validiere_Bloecke()">
        {% csrf_token %}
        <div class="form-group">
          <label for="anzahl_studenten">Wie viele Studenten sollen verteilt werden? (noch {{ anzahl_freie_studenten }} frei)</label>
          <div class="row">
            <div class="col-sm-4 col-md-4 col-lg-2">
              <input type="number" name="anzahl_studenten" id="anzahl_studenten" class="form-control" value="120" min="0"/>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="bloecke">Auf welche Blöcke sollen sie verteilt werden? (<a href="javascript:alle_Bloecke_waehlen();">alle anwählen</a>)</label>
          <p class="text-danger" id="blockwarnung" style="display: none;">Ein Block muss mindestens ausgewählt werden!</p>
          <div id="bloecke" name="bloecke">
            {% for b in bloecke %}
            <div class="checkbox">
              <label><input type="checkbox" name="block" value="{{ b.id }}" /> {{ b.name }}</label>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="form-group">
          <label for="blocklimit">Wie viele Studenten sollen maximal pro Block verteilt werden? </label>
          <div class="row">
            <div class="col-sm-4 col-md-4 col-lg-2">
              <input type="number" name="blocklimit" id="blocklimit" class="form-control" value="30" min="0"/>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="checkbox">
            <label>
              <input type="checkbox" name="loeschen" value="true" />
              automatisch verteilte Plätze löschen
            </label>
          </div>
        </div>
        <p>
          <button type="submit" class="btn btn-primary"{% if laufende_Platzverteilung %} disabled="disabled"{% endif %}>Studenten verteilen</button>
        </p>
      </form>
    </div>
  </div>
</div>
{% endblock %}